# Generated by Django 5.1 on 2024-10-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
